### ISSUE TITLE
Govee on homebridge

### ISSUE THREAD

**Issue by Stetocasa** [ddxtanx/GoveeAPI#3]
Hi, we are people looking for a developer to create a plugin to control Govee lights on Homebridge.

**Comment by bwp91** [comment]
I’ve read there is a public api for govee?
any documentation?

**Comment by Stetocasa** [comment]
> I’ve read there is a public api for govee?
> 
> any documentation?

https://github.com/ddxtanx/GoveeAPI

**Comment by Stetocasa** [comment]
> I’ve read there is a public api for govee?
> 
> any documentation?

I have also PDF from Govee if you send me your email I can forward

**Comment by bwp91** [comment]
it's okay i've made a start on a plugin homebridge-govee.

it lacks any functionality at the moment but it's a base!

**Comment by Stetocasa** [comment]
> it's okay i've made a start on a plugin homebridge-govee.
> 
> it lacks any functionality at the moment but it's a base!

A simple switch on/off will be amazing for me.
I installed in a critical position and I can remove it without destroy the wall (very bad decision during the construction).
I'm managing by power Wifi switch but every on the ledstrip check an initial RGB cycle (it seems to be a xmas tree)

**Comment by bwp91** [comment]
which model do you have?

**Comment by Stetocasa** [comment]
> which model do you have?

H6159

**Comment by bwp91** [comment]
it's slow steady progress but if you update to v0.0.7 you should be able to turn your light on and off through homebridge/homekit.

all other functionality is still a work in progress!

**Comment by Stetocasa** [comment]
Thanks. How Can I config?

> it's slow steady progress but if you update to v0.0.7 you should be able to turn your light on and off through homebridge/homekit.
> 
> 
> 
> all other functionality is still a work in progress!

**Comment by Stetocasa** [comment]
> it's slow steady progress but if you update to v0.0.7 you should be able to turn your light on and off through homebridge/homekit.
> 
> 
> 
> all other functionality is still a work in progress!

Hoobs not updated yet the last version ![image](https://user-images.githubusercontent.com/70729310/93462462-abfef200-f8e6-11ea-8dbf-6a99701d2e0c.png)

**Comment by bwp91** [comment]
hoobs can take a while to refresh updates.
you also need to obtain an API key from your govee app via My Profile -> About Us -> Apply for API key

**Comment by bwp91** [comment]
and after you install the plugin then it will guide you in the right place to add the api key to the hoobs config

**Comment by Stetocasa** [comment]
> and after you install the plugin then it will guide you in the right place to add the api key to the hoobs config

Done, I don't know why one strip work (on/off) the other no
Any suggestion ?![image](https://user-images.githubusercontent.com/70729310/93468322-1156e100-f8ef-11ea-8f93-51b8b00b5ed2.jpeg)![image](https://user-images.githubusercontent.com/70729310/93468338-174cc200-f8ef-11ea-9ba3-ed38c10444e3.jpeg)![image](https://user-images.githubusercontent.com/70729310/93468347-1b78df80-f8ef-11ea-9054-c58e2e3397e6.jpeg)

**Comment by bwp91** [comment]
Are they both the same model?
Can you turn on the "debug logging" setting and then control the one that doesn't work - and if there is an error then it will be visible in the HOOBS logs.

**Comment by Stetocasa** [comment]
> Are they both the same model?
> 
> Can you turn on the "debug logging" setting and then control the one that doesn't work - and if there is an error then it will be visible in the HOOBS logs.

I think that the issue is the Wifi connection on Govee app (one of the two strips is not connected)
![image](https://user-images.githubusercontent.com/70729310/93477470-55e87980-f8fb-11ea-9521-be226a2b3d93.jpeg)

**Comment by bwp91** [comment]
This plugin does need the device to be connected to the wifi. As it uses a web api for device control.

**Comment by Stetocasa** [comment]
> This plugin does need the device to be connected to the wifi. As it uses a web api for device control.
> 

![image](https://user-images.githubusercontent.com/70729310/93484393-25580e00-f902-11ea-87ef-5dd5d60827fd.png)
![image](https://user-images.githubusercontent.com/70729310/93484464-39037480-f902-11ea-9de0-cb3aa5d9ca6c.png)
![image](https://user-images.githubusercontent.com/70729310/93484507-4587cd00-f902-11ea-920e-b639a3a5a6b3.png)
![image](https://user-images.githubusercontent.com/70729310/93484522-4a4c8100-f902-11ea-9d72-7ffe06b123ba.png)

**Comment by Stetocasa** [comment]
> This plugin does need the device to be connected to the wifi. As it uses a web api for device control.
> 

Any indication about the log ?

**Comment by bwp91** [comment]
Have you got this device to work at all?

**Comment by bwp91** [comment]
The error message is "can not found device state in database"
which seems like a govee error rather than a plugin error.

**Comment by Stetocasa** [comment]
> The error message is "can not found device state in database"
> which seems like a govee error rather than a plugin error.

I'm sure that something wrong not in plugin but in Govee app
I added a third led strips and work well on plugin and also in Govee app is connected to Wifi ![image](https://user-images.githubusercontent.com/70729310/93583491-39544c00-f9a4-11ea-9c0f-99f26f2de22b.png)

**Comment by Stetocasa** [comment]
@bwp91 Do you have plan to introduce in the future additional control to the plugin?
Color or music mode

**Comment by bwp91** [comment]
Yes, eventually :) My next plans are brightness and colour control.
No time frames though as obviously depends on how much of my free time I can give to this plugin!

**Comment by Stetocasa** [comment]
> Yes, eventually :) My next plans are brightness and colour control.
> 
> No time frames though as obviously depends on how much of my free time I can give to this plugin!

Fantastic! Any idea about color control? Just because I planned to change the led strip before you started this plugin. Now if I will can control the color I will not change

**Comment by Stetocasa** [comment]
> Yes, eventually :) My next plans are brightness and colour control.
> 
> No time frames though as obviously depends on how much of my free time I can give to this plugin!

Idea referring when you think to introduce it

**Comment by bwp91** [comment]
I’ll see what I can do this weekend. Then you definitely owe me a beer 🍺 🤣🤣

**Comment by Stetocasa** [comment]
> I’ll see what I can do this weekend. Then you definitely owe me a beer 🍺 🤣🤣

Man you win more than a beer! Where do U live

**Comment by bwp91** [comment]
Please try v0.1.0
There are probably going to be errors...
So let me know!

**Comment by Stetocasa** [comment]
> Please try v0.1.0
> 
> There are probably going to be errors...
> 
> So let me know!

What's the command on terminal? On hoobs already there is 0.08

**Comment by bwp91** [comment]
> hoobs can take a while to refresh updates.

easiest to wait for the update to appear.

or make a transition to Homebridge itself...!

**Comment by Stetocasa** [comment]
> > hoobs can take a while to refresh updates.
> 
> 
> 
> easiest to wait for the update to appear.
> 
> 
> 
> or make a transition to Homebridge itself...!
> 
> 
Ok man awaiting for hoobs.

**Comment by Stetocasa** [comment]
> > hoobs can take a while to refresh updates.
> 
> 
> 
> easiest to wait for the update to appear.
> 
> 
> 
> or make a transition to Homebridge itself...!
> 
> 

What's the changes?

**Comment by bwp91** [comment]
did you try it?

**Comment by Stetocasa** [comment]
> did you try it?

Updated but not work
Now is not a switch but a dimmer 
We lost also the config ![image](https://user-images.githubusercontent.com/70729310/93661999-aaefd100-fa5c-11ea-8e12-f207f595e30e.png)
![image](https://user-images.githubusercontent.com/70729310/93662006-b0e5b200-fa5c-11ea-9bc1-7491795430d9.jpeg)![image](https://user-images.githubusercontent.com/70729310/93662009-b3e0a280-fa5c-11ea-880c-fa98fcb59116.jpeg)

**Comment by Stetocasa** [comment]
How can downgrade in the previous one?

**Comment by Stetocasa** [comment]
Cancelled and installed again. Now work well. Color and dimmer
TOP

**Comment by Stetocasa** [comment]
If I can suggest for the future, this Govee led is a good led because the control also has a microphone that show the light according the sound perceived 
Is a music mode on Govee app ![image](https://user-images.githubusercontent.com/70729310/93662224-f0150280-fa5e-11ea-9422-30e07624582d.jpeg)

**Comment by bwp91** [comment]
Music mode isn’t supported by the api. you can see from the api document that the only things it supports is:
- on/off
- brightness, and
- colour control

But i’m glad the colours work okay!

**Comment by Stetocasa** [comment]
> Music mode isn’t supported by the api. you can see from the api document that the only things it supports is:
> 
> - on/off
> 
> - brightness, and
> 
> - colour control
> 
> 
> 
> But i’m glad the colours work okay!

Yes man work fine!

**Comment by bwp91** [comment]
Anything other features that you'd be interested in seeing in this plugin, two things to think about:
* how could it be implemented into HomeKit/Home App (for example music mode...?)
* getting in contact with Govee asking them to support it in the web api 

Thanks!

**Comment by Stetocasa** [comment]
@bwp91 In the last days the light is on 39% brightness when turn on. In the reality the real brightness is to 100% but in homekit shows 39%

**Comment by bwp91** [comment]
This is interesting as the device i created the plugin with used a brightness scale of 0->254.
So I had to scale this govee range 0-254 to the homekit scale of 0-100 (by diving by 2.54)
It’s interesting that your govee brightness of 100% diving by the 2.54 is 39%.
So perhaps your device actually sends the brightness to homebridge on a scale of 0-100 rather than 0-254.

Which makes me think:
- Does one govee device measure brightness from 0-254 and your specific model is different ie the range is 0-100?
- Has Govee changed something in their systems for all models?
- What do I do with regards to changing the plugin which would definitely work for you but potentially stop it working for other users!

**Comment by bwp91** [comment]
Since this is new plugin i don’t have a “base” of other users to ask if they are experiencing the same

**Comment by bwp91** [comment]
Which model do you have?

**Comment by Stetocasa** [comment]
> Which model do you have?

H6159

**Comment by Stetocasa** [comment]
> Which model do you have?

![image](https://user-images.githubusercontent.com/70729310/95388769-1a860d00-08f3-11eb-9126-8300a79fa636.jpeg)

**Comment by bwp91** [comment]
@Stetocasa your original comment:

> In the last days the light is on 39% brightness

Wanted to also check, “in the last days”:
* have you changed the “mode” that the device is in?
* have you upgraded firmware?
* can you think of any other reason why this might have changed?

**Comment by Stetocasa** [comment]
> @Stetocasa your original comment:
> 
> 
> 
> > In the last days the light is on 39% brightness
> 
> 
> 
> Wanted to also check, “in the last days”:
> 
> * have you changed the “mode” that the device is in?
> 
> * have you upgraded firmware?
> 
> * can you think of any other reason why this might have changed?
> 
> 

No changes from my side
Just upgraded the plugin every time

**Comment by bwp91** [comment]
Please try updating to v1.3.1 and restart homenridge. hopefully this will be fixed

**Comment by Stetocasa** [comment]
> Please try updating to v1.3.1 and restart homenridge. hopefully this will be fixed 

Which is the right command to write on terminal to update?
I have hoobs and the new update is not available yet

**Comment by bwp91** [comment]
I’m not sure with HOOBS as I have never used it. Just a waiting game 😅

**Comment by Stetocasa** [comment]
> I’m not sure with HOOBS as I have never used it. Just a waiting game 😅

Inside hoobs there is the Mac terminal, it's just add the command

**Comment by bwp91** [comment]
Any luck?

**Comment by Stetocasa** [comment]
> Any luck?

Updated. Now work perfectly

**Comment by bwp91** [comment]
Excellent.

I would like to suggest something. Unless you are a collaborator on this @ddxtanx / GoveeAPI repo.

Your original issue on this repo was request for homebridge support which I believe I have implemented so this issue should be closed.

Any further issues you encounter I invite you to create an issue on the designated repo for my plugin at bwp91/homebridge-govee.

Then it’s easier for me to keep an eye on issues that people have 😀

But glad it’s working for you again!

**Comment by Stetocasa** [comment]
> Excellent.
> 
> 
> 
> I would like to suggest something. Unless you are a collaborator on this @ddxtanx / GoveeAPI repo.
> 
> 
> 
> Your original issue on this repo was request for homebridge support which I believe I have implemented so this issue should be closed.
> 
> 
> 
> Any further issues you encounter I invite you to create an issue on the designated repo for my plugin at bwp91/homebridge-govee.
> 
> 
> 
> Then it’s easier for me to keep an eye on issues that people have 😀
> 
> 
> 
> But glad it’s working for you again!

Absolutely 
Thanks for you great job

**Comment by Stetocasa** [comment]
@bwp91 Any potential issue with the plug-in after update the app?![image](https://user-images.githubusercontent.com/70729310/100253320-3dbb5900-2f41-11eb-9f97-c0ee3f85aecb.png)

**Comment by bwp91** [comment]
the govee api (that the plugin uses) and the govee app are two very different things and one shouldn’t affect the other. 
ive been on the new version of the app with no problems with the plugin!
