### ISSUE TITLE
Read data from device

### ISSUE THREAD

**Issue by fjcaetano** [ddxtanx/GoveeAPI#4]
Let me start by thanking you for this library. It's a great starting point and connecting to the device using BLE is much more responsive than using the Govee public API.

I'd like to further enhance this lib, and I think the first thing that needs to be added is reading data from the device, including it's current state. Do you have any idea how to do that or could you provide me some guidance on how to investigate this and possible figure out the BLE commands?

**Comment by ddxtanx** [comment]
If I recall correctly, gattlib (and I think the BLE protocol itself as well) provides a read command, although I think I may have tried it previously without success. If that does work in any case, that should provide a method by which to obtain the information on the device.

**Comment by fjcaetano** [comment]
I'm not familiar with gattlib and gatttool or with low level BLE in general, so I'm not 100% sure of what I'm doing, but I couldn't figure out a way to read brightness and color data from the device. These are my findings:

- If I connect to the device and sweep the described handles `0x0001 ~ 0x001a` I always get the same data for each handle, regardless of the state of the device.
- I am notified of brightness changes on handle `0x0011` but it always returns the same data regardless of the brightness level `33 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 37`
- Updating the color while connected does not trigger a notification
