### ISSUE TITLE
How do I install and then how do I use it

### ISSUE THREAD

**Issue by WestheadJ** [ddxtanx/GoveeAPI#5]
Hello, I'm having an issue trying to install this on my raspberry pi, I also don't see anywhere that shows me how to use this package

**Comment by felixwttr** [comment]
same question here

**Comment by ddxtanx** [comment]
Sorry I didn't include this in the original readme! To 'install' this, all you'll have to do is clone this repo and install the dependencies using ``pip3 install -r requirements.txt``. Note that there is the dependency on gattlib, so you should install this on a device that you've installed gattlib on or that has gattlib preinstalled (like raspis to my knowledge). To use it, you should try running ``python3 tool.py``. A little help menu will pop up and should describe the usage of the tool!
