### ISSUE TITLE
Doesn't work with H6008

### ISSUE THREAD

**Issue by BrettMeirhofer** [ddxtanx/GoveeAPI#6]
https://us.govee.com/products/govee-wi-fi-bluetooth-led-bulbs-2-pack

Seems to connect to the device well enough but the device doesn't respond to the commands.

Changed H6008_1996 color to (0, 0, 255)
Changed H6008_1996 color to (255, 0, 0)
(I get output but no error and no results)

I'm curious as to which Govee device this repo is designed for.

**Comment by ddxtanx** [comment]
This was designed specifically for the LED strips, not for the bulbs unfortunately… The only reason I was able to design this was due to the reverse engineering of the github user in the ReadMe. If there is a similar project for the bulbs, perhaps functionality could be integrated!

**Comment by BrettMeirhofer** [comment]
Are you referring to the H6127's?

**Comment by ddxtanx** [comment]
I believe that was the device type.
